name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: GillSans
      fonts:
        - asset: 'fonts/GillSans.ttc'
    - family: Canela
      fonts:
        - asset: 'fonts/Canela-Regular-Trial.otf'
    - family: Roboto Slab
      fonts:
        - asset: 'fonts/RobotoSlab-VariableFont_wght.ttf'
